### PR TITLE
Multi line diff fixes

### PR DESCRIPTION
**Pull request by renatoathaydes**
A few more tests and a small fix to the merge function.

### CODE REVIEW

**Comment by nelhage** [comment]
@renatoathaydes Does your change to the merge function fix a bug? All your tests seem to pass without it for me, and I would expect that `l.peek().is_some() && l.peek() == c.peek() && r.peek() == c.peek()` implies `r.peek().is_some()`, by transitivity of equality.

**Comment by renatoathaydes** [comment]
I modified the test that was failing after I realised that the elements of the diff are merged intentionally (I had expected the separator to not be included in any difference element), then didn't check if my change was needed... but I agree, it doesn't seem to be necessary, I will revert that.

BTW do you want to maintain a fork of this lib... seems like the original author is no longer interested?

**Comment by nelhage** [comment]
tbh I consider merging elements to be a bit of a bug in the original -- at least, confusing and surprising -- but it's behavior I preserved.

I pinged the author on the original ticket; If he doesn't respond to the offer to join as a maintainer, yeah, I'll likely time out and publish a fork, potentially taking the opportunity to fix a few things in a breaking way (e.g. not merging diff elements)

**Comment by nelhage** [comment]
Thanks!

**Comment by renatoathaydes** [comment]
Even though I already changed my code to account for that (which made it much more complicated, I can't see a good reason why this was done) I would welcome the change, TBH :)

**Comment by renatoathaydes** [comment]
@colin-kiegel you may want to check this discussion are you also seem interested in this lib.

**Comment by colin-kiegel** [comment]
Hi. Yes, I was already subscribed to this ticket :-)

I'm curious, what behaviour do you mean by _merging elements_?
I [don't see](https://github.com/nelhage/difference.rs/blob/master/src/lib.rs#L195-L221) a separator included in any difference element.

Can you give something like an end-user example of what behaviour is surprising?

**Comment by renatoathaydes** [comment]
@colin-kiegel see the [tests I added](https://github.com/renatoathaydes/difference.rs/blob/cfaf2e913f05e9714418a056f231a8422df8aabe/src/lib.rs#L258).

**Comment by colin-kiegel** [comment]
@renatoathaydes I see, thx. Now I remember that I actually split all difference elements by "\n" again, when formatting lines in `pretty_assertions`. But I also have a use case for the merging behaviour, e.g. when I want to format chunks of Adds and Rems as a whole, like in `The [-fast red-]{+quick brown+} fox jumps over the lazy dog`. I actually have both use cases in `pretty_assertions` - so I have no real preference.

But I agree, that the merging behaviour was a bit counter-intuitive to me at first, too. This is because the edit distance is defined as the count of _non-merged_ `Add`s+`Rem`s. I would have expected to find non-merged difference elements by default, reflecting the edit distance.

I stumbled over some other ambiguities too. The following are equivalent (with split on " ").

Add before Rem:
```rust
[
    Add("quick"),
    Add("brown"),
    Rem("fast"),
    Rem("red"),
]
```

Rem before Add:
```rust
[
    Rem("fast"),
    Rem("red"),
    Add("quick"),
    Add("brown"),
]
```

Add+Rem mixed:
```rust
[
    Add("quick"),
    Rem("fast"),
    Add("brown"),
    Rem("red"),
]
```

...

It would be nice, if the difference crate would state in it's docs whether there is any "normalization" of these ambiguities, e.g. whether `Add`s will always appear bundled and before (bundled) `Rem`s. This way you would know, if you can _rely_ on any ordering or not. :-)

**Pull request merged**
